apiVersion: v2
name: kubeai-chatbot
description: KubeAI Chatbot server for integration with Slack that offers detailed management of Kubernetes clusters
home: https://github.com/KongZ/kubeai-chatbot
icon: https://github.com/KongZ/kubeai-chatbot/blob/main/docs/kubeai-chatbot.png?raw=true
type: application
version: 0.1.0
appVersion: "0.1.0"
sources:
  - https://www.github.com/KongZ/kubeai-chatbot
maintainers:
  - name: KongZ
    email: goonohc@gmail.com
keywords:
  - k8s
  - kubernetes
  - ai
  - slack
  - chatbot
  - devops
  - infrastructure
  - aws
  - gcp
  - eks
  - gke